// Biblioteca de ejercicios de serie — se siembra automáticamente la primera vez
// que un entrenador entra a "Ejercicios" y aún no tiene ninguno en su base de
// datos. El entrenador decide luego a qué especialidad pertenece cada uno;
// aquí solo se clasifican por grupo muscular.
export interface DefaultExercise { name: string; category: string }

export const DEFAULT_EXERCISE_LIBRARY: DefaultExercise[] = [
  // Pecho
  { name: 'Press banca', category: 'Pecho' },
  { name: 'Press banca inclinado', category: 'Pecho' },
  { name: 'Press banca declinado', category: 'Pecho' },
  { name: 'Press inclinado mancuernas', category: 'Pecho' },
  { name: 'Press declinado mancuernas', category: 'Pecho' },
  { name: 'Press de pecho en máquina', category: 'Pecho' },
  { name: 'Aperturas con mancuernas (planas)', category: 'Pecho' },
  { name: 'Aperturas inclinadas con mancuernas', category: 'Pecho' },
  { name: 'Cruces en polea alta (cable cross)', category: 'Pecho' },
  { name: 'Cruces en polea baja', category: 'Pecho' },
  { name: 'Peck deck (contractor de pecho)', category: 'Pecho' },
  { name: 'Fondos en paralelas (pecho)', category: 'Pecho' },
  { name: 'Flexiones (push-ups)', category: 'Pecho' },
  { name: 'Press con banda elástica', category: 'Pecho' },
  { name: 'Pullover con mancuerna', category: 'Pecho' },
  { name: 'Press banca con mancuernas', category: 'Pecho' },
  { name: 'Press banca con agarre cerrado', category: 'Pecho' },
  { name: 'Press inclinado en máquina', category: 'Pecho' },
  { name: 'Press en multipower (smith machine)', category: 'Pecho' },
  { name: 'Aperturas en máquina (pec deck inverso)', category: 'Pecho' },
  { name: 'Flexiones con lastre', category: 'Pecho' },
  { name: 'Flexiones declinadas', category: 'Pecho' },
  { name: 'Flexiones con palmada', category: 'Pecho' },
  { name: 'Cruces en polea media', category: 'Pecho' },
  { name: 'Press con un solo brazo en polea', category: 'Pecho' },

  // Espalda
  { name: 'Dominadas pronas', category: 'Espalda' },
  { name: 'Dominadas supinas (chin-up)', category: 'Espalda' },
  { name: 'Dominadas agarre neutro', category: 'Espalda' },
  { name: 'Dominadas lastradas', category: 'Espalda' },
  { name: 'Jalón al pecho (polea)', category: 'Espalda' },
  { name: 'Pulldown agarre neutro', category: 'Espalda' },
  { name: 'Pulldown agarre estrecho', category: 'Espalda' },
  { name: 'Remo con barra', category: 'Espalda' },
  { name: 'Remo Pendlay', category: 'Espalda' },
  { name: 'Remo con mancuerna a una mano', category: 'Espalda' },
  { name: 'Remo en T (T-bar row)', category: 'Espalda' },
  { name: 'Remo en máquina sentado', category: 'Espalda' },
  { name: 'Remo en polea baja (seated cable row)', category: 'Espalda' },
  { name: 'Peso muerto convencional', category: 'Espalda' },
  { name: 'Peso muerto rumano', category: 'Espalda' },
  { name: 'Peso muerto sumo', category: 'Espalda' },
  { name: 'Peso muerto piernas rígidas', category: 'Espalda' },
  { name: 'Pull-over en polea alta', category: 'Espalda' },
  { name: 'Face pull', category: 'Espalda' },
  { name: 'Buenos días (good morning)', category: 'Espalda' },
  { name: 'Remo invertido (inverted row)', category: 'Espalda' },
  { name: 'Remo con banda elástica', category: 'Espalda' },
  { name: 'Remo Meadows', category: 'Espalda' },
  { name: 'Jalón al pecho agarre amplio', category: 'Espalda' },
  { name: 'Jalón tras nuca', category: 'Espalda' },
  { name: 'Australian pull-up', category: 'Espalda' },
  { name: 'Peso muerto con trap bar (hex bar)', category: 'Espalda' },
  { name: 'Peso muerto déficit', category: 'Espalda' },
  { name: 'Remo en máquina Hammer', category: 'Espalda' },
  { name: 'Hiperextensiones (banco lumbar)', category: 'Espalda' },
  { name: 'Superman', category: 'Espalda' },
  { name: 'Peso muerto a una pierna', category: 'Espalda' },
  { name: 'Extensión lumbar en máquina', category: 'Espalda' },
  { name: 'Encogimiento de hombros con barra (shrugs)', category: 'Espalda' },
  { name: 'Encogimiento de hombros con mancuernas', category: 'Espalda' },
  { name: 'Remo al cuello (upright row)', category: 'Espalda' },
  { name: 'Farmer walk (paseo del granjero)', category: 'Espalda' },

  // Hombros
  { name: 'Press militar con barra', category: 'Hombros' },
  { name: 'Press militar sentado', category: 'Hombros' },
  { name: 'Press de hombro con mancuernas', category: 'Hombros' },
  { name: 'Press Arnold', category: 'Hombros' },
  { name: 'Press de hombro en máquina', category: 'Hombros' },
  { name: 'Press tras nuca', category: 'Hombros' },
  { name: 'Elevaciones laterales con mancuernas', category: 'Hombros' },
  { name: 'Elevaciones laterales en polea', category: 'Hombros' },
  { name: 'Elevaciones laterales en máquina', category: 'Hombros' },
  { name: 'Elevaciones frontales con mancuernas', category: 'Hombros' },
  { name: 'Elevaciones frontales con barra', category: 'Hombros' },
  { name: 'Pájaros (elevación posterior con mancuernas)', category: 'Hombros' },
  { name: 'Pájaros en máquina (reverse peck deck)', category: 'Hombros' },
  { name: 'Press Bradford', category: 'Hombros' },
  { name: 'Landmine press', category: 'Hombros' },
  { name: 'Push press', category: 'Hombros' },
  { name: 'Elevaciones laterales inclinado (lean-away)', category: 'Hombros' },
  { name: 'Elevaciones laterales con banda', category: 'Hombros' },
  { name: 'Y-raises', category: 'Hombros' },
  { name: 'Press de hombro con kettlebell', category: 'Hombros' },
  { name: 'Press militar en multipower', category: 'Hombros' },
  { name: 'Cuban press', category: 'Hombros' },
  { name: 'Rotación externa de hombro en polea', category: 'Hombros' },

  // Bíceps
  { name: 'Curl de bíceps con barra', category: 'Bíceps' },
  { name: 'Curl de bíceps con barra Z', category: 'Bíceps' },
  { name: 'Curl de bíceps con mancuernas', category: 'Bíceps' },
  { name: 'Curl de bíceps alterno', category: 'Bíceps' },
  { name: 'Curl martillo', category: 'Bíceps' },
  { name: 'Curl en banco Scott (predicador)', category: 'Bíceps' },
  { name: 'Curl concentrado', category: 'Bíceps' },
  { name: 'Curl en polea baja', category: 'Bíceps' },
  { name: 'Curl 21s', category: 'Bíceps' },
  { name: 'Curl spider', category: 'Bíceps' },
  { name: 'Curl con banda elástica', category: 'Bíceps' },
  { name: 'Curl en máquina', category: 'Bíceps' },
  { name: 'Curl inclinado con mancuernas', category: 'Bíceps' },
  { name: 'Curl con cuerda en polea', category: 'Bíceps' },

  // Tríceps
  { name: 'Press francés con barra', category: 'Tríceps' },
  { name: 'Press francés con mancuerna', category: 'Tríceps' },
  { name: 'Extensión de tríceps en polea alta', category: 'Tríceps' },
  { name: 'Extensión de tríceps con cuerda', category: 'Tríceps' },
  { name: 'Patada de tríceps (kickback)', category: 'Tríceps' },
  { name: 'Fondos de tríceps en banco', category: 'Tríceps' },
  { name: 'Press cerrado (close grip bench press)', category: 'Tríceps' },
  { name: 'Extensión de tríceps tras nuca con mancuerna', category: 'Tríceps' },
  { name: 'Extensión de tríceps en polea a una mano', category: 'Tríceps' },
  { name: 'Press JM', category: 'Tríceps' },
  { name: 'Fondos en paralelas (tríceps)', category: 'Tríceps' },
  { name: 'Extensión de tríceps con banda', category: 'Tríceps' },

  // Antebrazo
  { name: 'Curl de muñeca con barra', category: 'Antebrazo' },
  { name: 'Curl de muñeca inverso', category: 'Antebrazo' },
  { name: 'Dead hang (colgarse de la barra)', category: 'Antebrazo' },
  { name: 'Paseo del granjero (agarre)', category: 'Antebrazo' },
  { name: 'Curl de muñeca con mancuerna', category: 'Antebrazo' },
  { name: 'Pinza de discos (plate pinch)', category: 'Antebrazo' },
  { name: 'Enrollado de muñeca (wrist roller)', category: 'Antebrazo' },

  // Piernas
  { name: 'Sentadilla con barra (back squat)', category: 'Piernas' },
  { name: 'Sentadilla frontal (front squat)', category: 'Piernas' },
  { name: 'Sentadilla goblet', category: 'Piernas' },
  { name: 'Sentadilla búlgara', category: 'Piernas' },
  { name: 'Sentadilla hack (hack squat)', category: 'Piernas' },
  { name: 'Sentadilla sumo', category: 'Piernas' },
  { name: 'Prensa de piernas (leg press)', category: 'Piernas' },
  { name: 'Zancadas (lunges)', category: 'Piernas' },
  { name: 'Zancadas con barra', category: 'Piernas' },
  { name: 'Extensión de cuádriceps en máquina', category: 'Piernas' },
  { name: 'Step up (subida al cajón)', category: 'Piernas' },
  { name: 'Sissy squat', category: 'Piernas' },
  { name: 'Sentadilla con salto (jump squat)', category: 'Piernas' },
  { name: 'Sentadilla isométrica en pared (wall sit)', category: 'Piernas' },
  { name: 'Zancadas caminando', category: 'Piernas' },
  { name: 'Zancadas inversas', category: 'Piernas' },
  { name: 'Sentadilla Smith machine', category: 'Piernas' },
  { name: 'Sentadilla pistol (a una pierna)', category: 'Piernas' },
  { name: 'Sentadilla con banda (mini band)', category: 'Piernas' },
  { name: 'Curl femoral tumbado', category: 'Piernas' },
  { name: 'Curl femoral sentado', category: 'Piernas' },
  { name: 'Curl femoral de pie', category: 'Piernas' },
  { name: 'Peso muerto rumano (femoral)', category: 'Piernas' },
  { name: 'Nordic curl', category: 'Piernas' },
  { name: 'Curl femoral con balón suizo (stability ball)', category: 'Piernas' },
  { name: 'Peso muerto rumano a una pierna', category: 'Piernas' },
  { name: 'Buenos días con barra (femoral)', category: 'Piernas' },
  { name: 'Elevación de talones de pie (gemelo)', category: 'Piernas' },
  { name: 'Elevación de talones sentado', category: 'Piernas' },
  { name: 'Elevación de talones en prensa', category: 'Piernas' },
  { name: 'Elevación de talones a una pierna', category: 'Piernas' },
  { name: 'Elevación de talones en sentadilla hack', category: 'Piernas' },
  { name: 'Saltos a la comba (gemelo)', category: 'Piernas' },

  // Glúteos
  { name: 'Hip thrust', category: 'Glúteos' },
  { name: 'Hip thrust a una pierna', category: 'Glúteos' },
  { name: 'Puente de glúteo (glute bridge)', category: 'Glúteos' },
  { name: 'Patada de glúteo en polea', category: 'Glúteos' },
  { name: 'Abducción de cadera en máquina', category: 'Glúteos' },
  { name: 'Abducción de cadera con banda', category: 'Glúteos' },
  { name: 'Peso muerto sumo (glúteo)', category: 'Glúteos' },
  { name: 'Patada de burro (donkey kick)', category: 'Glúteos' },
  { name: 'Hip thrust en máquina', category: 'Glúteos' },
  { name: 'Puente de glúteo con barra', category: 'Glúteos' },
  { name: 'Sentadilla sumo con kettlebell (glúteo)', category: 'Glúteos' },
  { name: 'Cable kickback (polea baja)', category: 'Glúteos' },
  { name: 'Frog pump', category: 'Glúteos' },

  // Core
  { name: 'Plancha (plank)', category: 'Core' },
  { name: 'Plancha lateral', category: 'Core' },
  { name: 'Rueda abdominal (ab wheel)', category: 'Core' },
  { name: 'Crunch abdominal', category: 'Core' },
  { name: 'Crunch en polea (cable crunch)', category: 'Core' },
  { name: 'Elevación de piernas colgado', category: 'Core' },
  { name: 'Elevación de rodillas colgado', category: 'Core' },
  { name: 'Russian twist', category: 'Core' },
  { name: 'Mountain climbers', category: 'Core' },
  { name: 'Dragon flag', category: 'Core' },
  { name: 'Hollow body hold', category: 'Core' },
  { name: 'Sit-up', category: 'Core' },
  { name: 'Pallof press', category: 'Core' },
  { name: 'V-ups', category: 'Core' },
  { name: 'Bicicleta abdominal (bicycle crunch)', category: 'Core' },
  { name: 'Plancha con elevación de brazo/pierna', category: 'Core' },
  { name: 'Giro ruso con peso (weighted russian twist)', category: 'Core' },
  { name: 'Elevación de piernas tumbado', category: 'Core' },
  { name: 'Ab rollout en TRX', category: 'Core' },
  { name: 'Sit-up con disco', category: 'Core' },

  // Cardio
  { name: 'Carrera continua', category: 'Cardio' },
  { name: 'Sprints (carrera corta intensa)', category: 'Cardio' },
  { name: 'Bicicleta estática', category: 'Cardio' },
  { name: 'Elíptica', category: 'Cardio' },
  { name: 'Remo (máquina de remo)', category: 'Cardio' },
  { name: 'Assault bike / bici de aire', category: 'Cardio' },
  { name: 'Comba (saltar a la cuerda)', category: 'Cardio' },
  { name: 'Subir escaleras / stairmaster', category: 'Cardio' },
  { name: 'Natación', category: 'Cardio' },
  { name: 'Burpees', category: 'Cardio' },
  { name: 'Battle ropes (cuerdas de batalla)', category: 'Cardio' },
  { name: 'Mountain climbers (cardio)', category: 'Cardio' },
  { name: 'Jumping jacks', category: 'Cardio' },
  { name: 'Skipping (high knees)', category: 'Cardio' },
  { name: 'Senderismo / caminata rápida', category: 'Cardio' },
  { name: 'Ciclismo en ruta', category: 'Cardio' },

  // Funcional / Olímpico
  { name: 'Kettlebell swing', category: 'Funcional/Olímpico' },
  { name: 'Clean (cargada)', category: 'Funcional/Olímpico' },
  { name: 'Snatch (arrancada)', category: 'Funcional/Olímpico' },
  { name: 'Clean and jerk', category: 'Funcional/Olímpico' },
  { name: 'Thruster', category: 'Funcional/Olímpico' },
  { name: 'Wall ball', category: 'Funcional/Olímpico' },
  { name: 'Box jump (salto al cajón)', category: 'Funcional/Olímpico' },
  { name: 'Lanzamiento de balón medicinal (slam ball)', category: 'Funcional/Olímpico' },
  { name: 'Arrastre de trineo (sled push/pull)', category: 'Funcional/Olímpico' },
  { name: 'Turkish get-up', category: 'Funcional/Olímpico' },
  { name: 'Power clean', category: 'Funcional/Olímpico' },
  { name: 'Hang clean', category: 'Funcional/Olímpico' },
  { name: 'Split jerk', category: 'Funcional/Olímpico' },
  { name: 'Snatch balance', category: 'Funcional/Olímpico' },
  { name: 'Devil press', category: 'Funcional/Olímpico' },
  { name: 'Man maker', category: 'Funcional/Olímpico' },
  { name: 'Tire flip (volteo de neumático)', category: 'Funcional/Olímpico' },
  { name: 'Bear crawl', category: 'Funcional/Olímpico' },
  { name: 'Battle rope slam', category: 'Funcional/Olímpico' },
  { name: 'Sled drag (arrastre lateral)', category: 'Funcional/Olímpico' },
]
